# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fd439d2ea8a6fdb778bedf67edd91541"
name = "The Last Bundler On The Left"
application_url = "https://the-last-bundler-on-git-932c72-willowsoftstudio-5437s-projects.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_cart_transforms,read_cart_transforms,write_publications,read_publications"

[auth]
redirect_urls = [
  "https://the-last-bundler-on-the-left-q32x8aen4.vercel.app/api/auth/callback",
  "https://the-last-bundler-on-git-932c72-willowsoftstudio-5437s-projects.vercel.app/api/auth/callback",
  "https://the-last-bundler-on-the-left.vercel.app/api/auth/callback"
]
