query RunInput {
  cart {
    buyerIdentity {
      customer {
        purchasedDeals: metafield(namespace: "bundle_app", key: "purchased_deals") {
          value
        }
      }
    }
    lines {
      id
      quantity
      cost {
        amountPerQuantity {
          amount
        }
      }
      merchandise {
        ... on ProductVariant {
          id
          title
          sku
          product {
            id
            title
          }
        }
      }
      attribute(key: "_bundle_id") {
        value
      }
    }
  }
  # Read active bundle configuration mapping stored in app metafields
  shop {
    bundleMetafields: metafield(namespace: "bundle_app", key: "active_bundles") {
      value
    }
  }
}
