api_version = "2026-07"

[[extensions]]
type = "function"
name = "Bundle Cart Transform"
handle = "cart-transform"
uid = "723515e5-bc2e-45c6-6942-564c29099db8e998c0bc"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"

[[extensions.targeting]]
target = "cart.transform.run"
code_file = "dist/function.wasm"
export = "run"
input_query = "src/run.graphql"
